### ISSUE TITLE
404

### ISSUE THREAD

**Issue by kamushadenes** [zgmnkv/openwrt-dist#1]
Hello,

First of all, thank you very much for this repository. It really helped me with my C7.

Now, to the issue. Your repository links are all returning 404:

Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/base/Packages.gz.                                    
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/base/Packages.sig.                                   
Signature check failed.                                    
Remove wrong Signature file.                               
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/luci/Packages.gz.                                    
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/luci/Packages.sig.                                   
Signature check failed.                                    
Remove wrong Signature file.                               
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/management/Packages.gz.                              
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/management/Packages.sig.                             
Signature check failed.                                    
Remove wrong Signature file.                               
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/packages/Packages.gz.                                
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/packages/Packages.sig.                               
Signature check failed.                                    
Remove wrong Signature file.                               
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/routing/Packages.gz.                                 
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/routing/Packages.sig.                                
Signature check failed.                                    
Remove wrong Signature file.                               
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/telephony/Packages.gz.        

Collected errors:                                          
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/base/Packages.gz, wget returned 4.                                                                                                                  
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/base/Packages.sig, wget returned 4.                                                                                                                 
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/luci/Packages.gz, wget returned 4.                                                                                                                  
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/luci/Packages.sig, wget returned 4.                                                                                                                 
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/management/Packages.gz, wget returned 4.                                                                                                            
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/management/Packages.sig, wget returned 4.                                                                                                           
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/packages/Packages.gz, wget returned 4.                                                                                                              
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/packages/Packages.sig, wget returned 4.                                                                                                             
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/routing/Packages.gz, wget returned 4.                                                                                                               
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/routing/Packages.sig, wget returned 4.                                                                                                              
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/telephony/Packages.gz, wget returned 4.                                                                                                             
 * opkg_download: Failed to download https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/telephony/Packages.sig, wget returned 4.

**Comment by zgmnkv** [comment]
Hi,
Actually I found that there is LEDE project, which is a more active fork of OpenWRT https://lede-project.org/ , and there should be a release with support of new C7. I haven't tried it though.
I will look into your issue anyway.

**Comment by zgmnkv** [comment]
I don't see any errors from my router:
```Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/base/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_base.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/base/Packages.sig.
Signature check passed.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/luci/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_luci.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/luci/Packages.sig.
Signature check passed.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/management/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_management.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/management/Packages.sig.
Signature check passed.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_packages.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/packages/Packages.sig.
Signature check passed.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/routing/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_routing.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/routing/Packages.sig.
Signature check passed.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/telephony/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_telephony.
Downloading https://zgmnkv.github.io/openwrt-dist/ar71xx/packages/telephony/Packages.sig.
Signature check passed.
```
Maybe something wrong with your internet connection
